export {default as Home} from "./Home/home"
export {default as Login} from "./Login/login"
export {default as Cadastro} from "./Cadastro/cadastro"
export {default as Editar} from "./Editar/editar"
export {default as Dados} from "./Dados/dados"
